"""Run a `module:function` target under a profiler.

`mage profile -m package.module:function` writes one driver script and executes it
through the same path as a script target: in process for the Triton backend, as a
child process for Nsight. The driver embeds the call arguments, the warmup and
iteration counts, and the invocation directory, so the run does not depend on
shell quoting or on the working directory of the profiled process.
"""
from __future__ import annotations

import json
import tempfile
from pathlib import Path

DRIVER = '''"""Generated by `mage profile` to call one function under a profiler."""
import importlib
import sys

sys.path.insert(0, {cwd!r})

SPEC = {spec!r}
ARGS = {args!r}
KWARGS = {kwargs!r}
WARMUP = {warmup!r}
ITERATIONS = {iterations!r}
CAPTURE = {capture!r}
DISCARD_WARMUP = {discard_warmup!r}


def resolve(spec):
    """Return the callable named by a module:function spec."""
    module_name, _, attribute = spec.partition(":")
    target = importlib.import_module(module_name)
    for part in attribute.split("."):
        target = getattr(target, part)
    if not callable(target):
        raise SystemExit("{{}} is not callable".format(spec))
    return target


def discard_warmup():
    """Exclude warmup launches already recorded in this process."""
    from mage.profiler.backends.triton_profiler import TritonProfiler

    TritonProfiler.get_instance().discard()


def synchronize():
    import torch

    if torch.cuda.is_available():
        torch.cuda.synchronize()


def profiler(action):
    import torch

    cudart = torch.cuda.cudart()
    if action == "start":
        cudart.cudaProfilerStart()
    else:
        cudart.cudaProfilerStop()


def main():
    target = resolve(SPEC)
    for _ in range(WARMUP):
        target(*ARGS, **KWARGS)
    synchronize()
    if DISCARD_WARMUP:
        discard_warmup()
    if CAPTURE:
        profiler("start")
    try:
        for _ in range(ITERATIONS):
            target(*ARGS, **KWARGS)
        synchronize()
    finally:
        if CAPTURE:
            profiler("stop")


if __name__ == "__main__":
    main()
'''


def parse_target(spec: str) -> tuple[str, str]:
    """Split a `module:function` spec into its module and attribute path.

    Raises:
        ValueError: if the spec is not a dotted module and a dotted attribute.
    """
    module, separator, attribute = spec.partition(":")
    if not separator:
        raise ValueError(f"target must be written as module:function, got {spec!r}")
    if ":" in attribute:
        raise ValueError(f"target must contain a single ':', got {spec!r}")
    for label, name in (("module", module), ("function", attribute)):
        if not name or not all(part.isidentifier() for part in name.split(".")):
            raise ValueError(f"target {label} must be a dotted Python name, got {name!r}")
    return module, attribute


def write_driver(
    spec: str,
    *,
    cwd: str | Path,
    call_args: str = "[]",
    call_kwargs: str = "{}",
    warmup: int = 3,
    iterations: int = 1,
    capture: bool = False,
    discard_warmup: bool = False,
) -> Path:
    """Write a driver for `spec` into a new temporary directory and return its path.

    The caller removes the returned path's parent directory; the driver itself is
    disposable, so nothing it writes should be treated as evidence.

    Raises:
        ValueError: if the spec, the JSON arguments, or the counts are unusable.
    """
    parse_target(spec)
    if warmup < 0:
        raise ValueError(f"warmup must be zero or positive, got {warmup}")
    if iterations < 1:
        raise ValueError(f"iterations must be positive, got {iterations}")
    args = _json(call_args, "--call-args", list)
    kwargs = _json(call_kwargs, "--call-kwargs", dict)

    directory = Path(tempfile.mkdtemp(prefix="mage-target-"))
    script = directory / "mage_target.py"
    script.write_text(
        DRIVER.format(cwd=str(Path(cwd).resolve()), spec=spec, args=args, kwargs=kwargs,
                      warmup=warmup, iterations=iterations, capture=bool(capture),
                      discard_warmup=bool(discard_warmup)),
        encoding="utf-8",
    )
    return script


def _json(text: str, flag: str, expected: type):
    try:
        value = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"{flag} must be valid JSON: {exc}") from exc
    if not isinstance(value, expected):
        raise ValueError(f"{flag} must be a JSON {expected.__name__}, got {type(value).__name__}")
    return value
