// @generated by scripts/evolve.py -- do not edit by hand.
// wrapper template sha256 88e1bd98657504e3576879222b06115b9211901b2950e2abe54b76414bddb525 | body template sha256 0c235b979cd0bca28fe67f615d08f5755811cc38e06a508d49ecd92bed70313b
// generation 0
//
// Roles: `best` is the loop's incumbent configuration, `new` is the proposed
// candidate, both rendered from the same template. Select one with input.json
// "variant": "best" | "new"; a manifest without `variant` runs the committed
// kernels in this file's sibling `kernels` module.
#[cuda_module]
mod candidates {
    use super::*;

    /// (block_m, block_n, k_step) for `matmul_best`.
    pub const MATMUL_TILE_BEST: (u32, u32, u32) = (64, 64, 64);
    /// (threadIdx.x, threadIdx.y) for `matmul_best`.
    pub const MATMUL_BLOCK_BEST: (u32, u32) = (16, 16);
    /// (rows per block, threads per block) for `layernorm_best`.
    pub const LAYERNORM_CFG_BEST: (u32, u32) = (4, 256);
    pub const BEST_MATMUL_PARAMS_JSON: &str = r##"{"block":[64,64],"k_step":64,"quad_stage":true,"staging":"shared","thread_tile":[4,4],"transpose_a":true}"##;
    pub const BEST_LAYERNORM_PARAMS_JSON: &str = r##"{"threads":256,"warps_per_row":2}"##;

    /// (block_m, block_n, k_step) for `matmul_new`.
    pub const MATMUL_TILE_NEW: (u32, u32, u32) = (64, 64, 64);
    /// (threadIdx.x, threadIdx.y) for `matmul_new`.
    pub const MATMUL_BLOCK_NEW: (u32, u32) = (16, 16);
    /// (rows per block, threads per block) for `layernorm_new`.
    pub const LAYERNORM_CFG_NEW: (u32, u32) = (4, 256);
    pub const NEW_MATMUL_PARAMS_JSON: &str = r##"{"block":[64,64],"k_step":64,"quad_stage":true,"staging":"shared","thread_tile":[4,4],"transpose_a":true}"##;
    pub const NEW_LAYERNORM_PARAMS_JSON: &str = r##"{"threads":256,"warps_per_row":2}"##;

    /// incumbent matmul: 64x64 block tile, 4x4 per thread, K step 64.
    ///
    /// Generated from candidates_body.rs.tmpl; params {"block":[64,64],"k_step":64,"quad_stage":true,"staging":"shared","thread_tile":[4,4],"transpose_a":true}.
    #[kernel]
    pub fn matmul_best(
        n: u32,
        k: u32,
        a: &[f32],
        b: &[f32],
        mut out: DisjointSlice<f32, thread::Runtime2DIndex>,
    ) {
        use cuda_device::vector::{self, F32x4};

        static mut AT: SharedArray<f32, 4352, 16> = SharedArray::UNINIT;
        static mut BS: SharedArray<f32, 4096, 16> = SharedArray::UNINIT;
        let tx = thread::threadIdx_x() as usize;
        let ty = thread::threadIdx_y() as usize;
        let tid = ty * 16 + tx;
        let kk = k as usize;
        let nn = n as usize;
        let row0 = thread::blockIdx_y() as usize * 64;
        let col0 = thread::blockIdx_x() as usize * 64;
        let mut acc = [[0.0f32; 4]; 4];
        let mut step = 0usize;
        while step < kk {
            let b_quads = unsafe { core::ptr::addr_of_mut!(BS) }.cast::<F32x4>();
            let mut pass = 0usize;
            while pass < 4 {
                let q = tid + pass * 256;
                let row = q / 16;
                let col = (q % 16) * 4;
                let a_start = (row0 + row) * kk + step + col;
                if let Some(quad) = vector::as_vectors::<F32x4>(&a[a_start..a_start + 4]) {
                    let v = quad[0].as_slice();
                    // Store transposed (k-major) so each thread's 4 rows are contiguous.
                    unsafe {
                        AT[(col + 0) * 68 + row] = v[0];
                        AT[(col + 1) * 68 + row] = v[1];
                        AT[(col + 2) * 68 + row] = v[2];
                        AT[(col + 3) * 68 + row] = v[3];
                    }
                }
                let b_start = (step + row) * nn + col0 + col;
                if let Some(quad) = vector::as_vectors::<F32x4>(&b[b_start..b_start + 4]) {
                    unsafe {
                        *b_quads.add(row * 16 + col / 4) = quad[0];
                    }
                }
                pass += 1;
            }
            thread::sync_threads();
            let mut i = 0usize;
            while i < 64 {
                let a_base = core::ptr::addr_of!(AT).cast::<F32x4>();
                let mut av = [0.0f32; 4];
                let mut gr = 0usize;
                while gr < 1 {
                    // One 128-bit shared read for four of the rows this thread owns.
                    let lanes = unsafe {
                        (*a_base.add(i * 17 + ty * 1 + gr)).0
                    };
                    av[gr * 4 + 0] = lanes[0];
                    av[gr * 4 + 1] = lanes[1];
                    av[gr * 4 + 2] = lanes[2];
                    av[gr * 4 + 3] = lanes[3];
                    gr += 1;
                }
                let base = core::ptr::addr_of!(BS).cast::<F32x4>();
                let mut bv = [0.0f32; 4];
                let mut gc = 0usize;
                while gc < 1 {
                    let lanes = unsafe {
                        (*base.add(i * 16 + tx * 1 + gc)).0
                    };
                    bv[gc * 4 + 0] = lanes[0];
                    bv[gc * 4 + 1] = lanes[1];
                    bv[gc * 4 + 2] = lanes[2];
                    bv[gc * 4 + 3] = lanes[3];
                    gc += 1;
                }
                let mut r = 0usize;
                while r < 4 {
                    let mut c = 0usize;
                    while c < 4 {
                        acc[r][c] += av[r] * bv[c];
                        c += 1;
                    }
                    r += 1;
                }
                i += 1;
            }
            thread::sync_threads();
            step += 64;
        }
        // SAFETY: the host validated `m * n` output elements and launched exactly
        // one 64x64 tile per block, so every written cell is inside the
        // buffer and belongs to this block alone.
        let out_ptr = out.as_mut_ptr();
        let mut r = 0usize;
        while r < 4 {
            let mut c = 0usize;
            while c < 4 {
                unsafe {
                    *out_ptr.add((row0 + ty * 4 + r) * nn + col0 + tx * 4 + c) = acc[r][c];
                }
                c += 1;
            }
            r += 1;
        }
    }

    /// incumbent layer norm: 2 warp(s) per row, 4 rows per block.
    ///
    /// Generated from candidates_body.rs.tmpl; params {"threads":256,"warps_per_row":2}.
    #[kernel]
    pub fn layernorm_best(
        width: u32,
        rows: u32,
        x: &[f32],
        gamma: &[f32],
        beta: &[f32],
        mut out: DisjointSlice<f32>,
    ) {
        use cuda_device::vector::{self, F32x4};
        use cuda_device::warp;

        static mut PARTIAL: SharedArray<f32, 16> = SharedArray::UNINIT;
        let d = width as usize;
        let tid = thread::threadIdx_x() as usize;
        let lane = tid & 31;
        let warp = tid >> 5;
        let part = warp % 2;
        let row = thread::blockIdx_x() as usize * 4 + warp / 2;
        if row >= rows as usize {
            return;
        }
        let base = row * d;
        let Some(quads) = vector::as_vectors::<F32x4>(&x[base..base + d]) else {
            return;
        };
        let Some(gamma_quads) = vector::as_vectors::<F32x4>(gamma) else {
            return;
        };
        let Some(beta_quads) = vector::as_vectors::<F32x4>(beta) else {
            return;
        };
        // A warp owns the contiguous quad range [start, end) of its row, so a row
        // split across warps can never count an element twice. Sharing by whole
        // 32-lane steps alone would overlap whenever span is not a multiple of 32.
        let span = quads.len().div_ceil(2);
        let start = part * span;
        let end = core::cmp::min(start + span, quads.len());

        let mut sum = 0.0f32;
        let mut squares = 0.0f32;
        let mut q = start + lane;
        while q < end {
            let v = quads[q].as_slice();
            sum += v[0] + v[1] + v[2] + v[3];
            squares += v[0] * v[0] + v[1] * v[1] + v[2] * v[2] + v[3] * v[3];
            q += 32;
        }
        let mut offset = 16u32;
        while offset > 0 {
            sum += warp::shuffle_down_f32(sum, offset);
            squares += warp::shuffle_down_f32(squares, offset);
            offset >>= 1;
        }
        if lane == 0 {
            unsafe {
                PARTIAL[warp * 2] = sum;
                PARTIAL[warp * 2 + 1] = squares;
            }
        }
        thread::sync_threads();
        let row_warps = (warp / 2) * 2;
        let mut total = 0.0f32;
        let mut total_squares = 0.0f32;
        let mut w = 0usize;
        while w < 2 {
            total += unsafe { PARTIAL[(row_warps + w) * 2] };
            total_squares += unsafe { PARTIAL[(row_warps + w) * 2 + 1] };
            w += 1;
        }
        let mean = total / d as f32;
        let variance = total_squares / d as f32 - mean * mean;
        let inv = 1.0 / cuda_device::float::sqrt_rn_f32(variance + 1e-5);

        // SAFETY: the host validated `rows * width` output elements and each warp
        // owns the disjoint share of row `base`, so this view aliases no other warp.
        let out_row = unsafe { core::slice::from_raw_parts_mut(out.as_mut_ptr().add(base), d) };
        let Some(out_quads) = vector::as_vectors_mut::<F32x4>(out_row) else {
            return;
        };
        q = start + lane;
        while q < end {
            let v = quads[q].as_slice();
            let gv = gamma_quads[q].as_slice();
            let bv = beta_quads[q].as_slice();
            out_quads[q] = F32x4::new([
                (v[0] - mean) * inv * gv[0] + bv[0],
                (v[1] - mean) * inv * gv[1] + bv[1],
                (v[2] - mean) * inv * gv[2] + bv[2],
                (v[3] - mean) * inv * gv[3] + bv[3],
            ]);
            q += 32;
        }
    }


    /// candidate matmul: 64x64 block tile, 4x4 per thread, K step 64.
    ///
    /// Generated from candidates_body.rs.tmpl; params {"block":[64,64],"k_step":64,"quad_stage":true,"staging":"shared","thread_tile":[4,4],"transpose_a":true}.
    #[kernel]
    pub fn matmul_new(
        n: u32,
        k: u32,
        a: &[f32],
        b: &[f32],
        mut out: DisjointSlice<f32, thread::Runtime2DIndex>,
    ) {
        use cuda_device::vector::{self, F32x4};

        static mut AT: SharedArray<f32, 4352, 16> = SharedArray::UNINIT;
        static mut BS: SharedArray<f32, 4096, 16> = SharedArray::UNINIT;
        let tx = thread::threadIdx_x() as usize;
        let ty = thread::threadIdx_y() as usize;
        let tid = ty * 16 + tx;
        let kk = k as usize;
        let nn = n as usize;
        let row0 = thread::blockIdx_y() as usize * 64;
        let col0 = thread::blockIdx_x() as usize * 64;
        let mut acc = [[0.0f32; 4]; 4];
        let mut step = 0usize;
        while step < kk {
            let b_quads = unsafe { core::ptr::addr_of_mut!(BS) }.cast::<F32x4>();
            let mut pass = 0usize;
            while pass < 4 {
                let q = tid + pass * 256;
                let row = q / 16;
                let col = (q % 16) * 4;
                let a_start = (row0 + row) * kk + step + col;
                if let Some(quad) = vector::as_vectors::<F32x4>(&a[a_start..a_start + 4]) {
                    let v = quad[0].as_slice();
                    // Store transposed (k-major) so each thread's 4 rows are contiguous.
                    unsafe {
                        AT[(col + 0) * 68 + row] = v[0];
                        AT[(col + 1) * 68 + row] = v[1];
                        AT[(col + 2) * 68 + row] = v[2];
                        AT[(col + 3) * 68 + row] = v[3];
                    }
                }
                let b_start = (step + row) * nn + col0 + col;
                if let Some(quad) = vector::as_vectors::<F32x4>(&b[b_start..b_start + 4]) {
                    unsafe {
                        *b_quads.add(row * 16 + col / 4) = quad[0];
                    }
                }
                pass += 1;
            }
            thread::sync_threads();
            let mut i = 0usize;
            while i < 64 {
                let a_base = core::ptr::addr_of!(AT).cast::<F32x4>();
                let mut av = [0.0f32; 4];
                let mut gr = 0usize;
                while gr < 1 {
                    // One 128-bit shared read for four of the rows this thread owns.
                    let lanes = unsafe {
                        (*a_base.add(i * 17 + ty * 1 + gr)).0
                    };
                    av[gr * 4 + 0] = lanes[0];
                    av[gr * 4 + 1] = lanes[1];
                    av[gr * 4 + 2] = lanes[2];
                    av[gr * 4 + 3] = lanes[3];
                    gr += 1;
                }
                let base = core::ptr::addr_of!(BS).cast::<F32x4>();
                let mut bv = [0.0f32; 4];
                let mut gc = 0usize;
                while gc < 1 {
                    let lanes = unsafe {
                        (*base.add(i * 16 + tx * 1 + gc)).0
                    };
                    bv[gc * 4 + 0] = lanes[0];
                    bv[gc * 4 + 1] = lanes[1];
                    bv[gc * 4 + 2] = lanes[2];
                    bv[gc * 4 + 3] = lanes[3];
                    gc += 1;
                }
                let mut r = 0usize;
                while r < 4 {
                    let mut c = 0usize;
                    while c < 4 {
                        acc[r][c] += av[r] * bv[c];
                        c += 1;
                    }
                    r += 1;
                }
                i += 1;
            }
            thread::sync_threads();
            step += 64;
        }
        // SAFETY: the host validated `m * n` output elements and launched exactly
        // one 64x64 tile per block, so every written cell is inside the
        // buffer and belongs to this block alone.
        let out_ptr = out.as_mut_ptr();
        let mut r = 0usize;
        while r < 4 {
            let mut c = 0usize;
            while c < 4 {
                unsafe {
                    *out_ptr.add((row0 + ty * 4 + r) * nn + col0 + tx * 4 + c) = acc[r][c];
                }
                c += 1;
            }
            r += 1;
        }
    }

    /// candidate layer norm: 2 warp(s) per row, 4 rows per block.
    ///
    /// Generated from candidates_body.rs.tmpl; params {"threads":256,"warps_per_row":2}.
    #[kernel]
    pub fn layernorm_new(
        width: u32,
        rows: u32,
        x: &[f32],
        gamma: &[f32],
        beta: &[f32],
        mut out: DisjointSlice<f32>,
    ) {
        use cuda_device::vector::{self, F32x4};
        use cuda_device::warp;

        static mut PARTIAL: SharedArray<f32, 16> = SharedArray::UNINIT;
        let d = width as usize;
        let tid = thread::threadIdx_x() as usize;
        let lane = tid & 31;
        let warp = tid >> 5;
        let part = warp % 2;
        let row = thread::blockIdx_x() as usize * 4 + warp / 2;
        if row >= rows as usize {
            return;
        }
        let base = row * d;
        let Some(quads) = vector::as_vectors::<F32x4>(&x[base..base + d]) else {
            return;
        };
        let Some(gamma_quads) = vector::as_vectors::<F32x4>(gamma) else {
            return;
        };
        let Some(beta_quads) = vector::as_vectors::<F32x4>(beta) else {
            return;
        };
        // A warp owns the contiguous quad range [start, end) of its row, so a row
        // split across warps can never count an element twice. Sharing by whole
        // 32-lane steps alone would overlap whenever span is not a multiple of 32.
        let span = quads.len().div_ceil(2);
        let start = part * span;
        let end = core::cmp::min(start + span, quads.len());

        let mut sum = 0.0f32;
        let mut squares = 0.0f32;
        let mut q = start + lane;
        while q < end {
            let v = quads[q].as_slice();
            sum += v[0] + v[1] + v[2] + v[3];
            squares += v[0] * v[0] + v[1] * v[1] + v[2] * v[2] + v[3] * v[3];
            q += 32;
        }
        let mut offset = 16u32;
        while offset > 0 {
            sum += warp::shuffle_down_f32(sum, offset);
            squares += warp::shuffle_down_f32(squares, offset);
            offset >>= 1;
        }
        if lane == 0 {
            unsafe {
                PARTIAL[warp * 2] = sum;
                PARTIAL[warp * 2 + 1] = squares;
            }
        }
        thread::sync_threads();
        let row_warps = (warp / 2) * 2;
        let mut total = 0.0f32;
        let mut total_squares = 0.0f32;
        let mut w = 0usize;
        while w < 2 {
            total += unsafe { PARTIAL[(row_warps + w) * 2] };
            total_squares += unsafe { PARTIAL[(row_warps + w) * 2 + 1] };
            w += 1;
        }
        let mean = total / d as f32;
        let variance = total_squares / d as f32 - mean * mean;
        let inv = 1.0 / cuda_device::float::sqrt_rn_f32(variance + 1e-5);

        // SAFETY: the host validated `rows * width` output elements and each warp
        // owns the disjoint share of row `base`, so this view aliases no other warp.
        let out_row = unsafe { core::slice::from_raw_parts_mut(out.as_mut_ptr().add(base), d) };
        let Some(out_quads) = vector::as_vectors_mut::<F32x4>(out_row) else {
            return;
        };
        q = start + lane;
        while q < end {
            let v = quads[q].as_slice();
            let gv = gamma_quads[q].as_slice();
            let bv = beta_quads[q].as_slice();
            out_quads[q] = F32x4::new([
                (v[0] - mean) * inv * gv[0] + bv[0],
                (v[1] - mean) * inv * gv[1] + bv[1],
                (v[2] - mean) * inv * gv[2] + bv[2],
                (v[3] - mean) * inv * gv[3] + bv[3],
            ]);
            q += 32;
        }
    }

}
